In [2]:
import pandas as pd

In [ ]:
#ISNULL
#notnull

In [10]:
df =pd.read_csv('C:\\Users\\NIMJESX\\Documents\\My Folder\\ML Notes\\Excel-Dataset\\fortune.csv')
df.head(10)

,Rank,Company,Ticker,Sector,Industry,Profitable,Founder_is_CEO,FemaleCEO,Growth_in_Jobs,Change_in_Rank,...,Assets_M,CEO,Country,HeadquartersCity,HeadquartersState,Website,CompanyType,Footnote,MarketCap_Updated_M,Updated
0,1,Walmart,WMT,Retailing,General Merchandisers,yes,no,no,no,0,...,252399.0,C. Douglas McMillon,U.S.,Bentonville,Arkansas,https://www.stock.walmart.com,Public,"Figures are for fiscal year ended Jan. 31, 202...",559911.0,8/5/2024
1,2,NaN,NaN,Retailing,Internet Services and Retailing,yes,no,no,no,0,...,527854.0,Andrew R. Jassy,U.S.,Seattle,Washington,https://www.amazon.com,Public,"Market value as of July 15, 2024.",2005565.0,8/5/2024
2,3,NaN,NaN,Technology,"Computers, Office Equipment",yes,no,no,no,1,...,352583.0,Timothy D. Cook,U.S.,Cupertino,California,https://www.apple.com,Public,"Figures are for fiscal year ended Sept. 30, 20...",3594309.0,8/5/2024
3,4,NaN,NaN,Health Care,Health Care: Insurance and Managed Care,yes,no,no,yes,1,...,273720.0,Andrew P. Witty,U.S.,Minnetonka,Minnesota,https://www.unitedhealthgroup.com,Public,"Market value as of July 15, 2024.",474339.0,8/5/2024
4,5,NaN,NaN,Financials,Insurance: Property and Casualty (Stock),yes,no,no,yes,2,...,1069978.0,Warren E. Buffett,U.S.,Omaha,Nebraska,https://www.berkshirehathaway.com,Public,"Market value as of July 15, 2024.",937028.0,8/5/2024
5,6,NaN,NaN,Health Care,Health Care: Pharmacy and Other Services,yes,no,yes,no,0,...,249728.0,Karen S. Lynch,U.S.,Woonsocket,Rhode Island,https://www.cvshealth.com,Public,"Market value as of July 15, 2024.",73653.0,8/5/2024
6,7,Exxon Mobil,WMT,Energy,Petroleum Refining,yes,no,no,no,-4,...,376317.0,Darren W. Woods,U.S.,Spring,Texas,https://www.exxonmobil.com,Public,Excise taxes have been deducted. Market value ...,516824.0,8/5/2024
7,8,Alphabet,GOOGL,Technology,Internet Services and Retailing,yes,no,no,no,0,...,402392.0,Sundar Pichai,U.S.,Mountain View,California,https://www.abc.xyz,Public,"Market value as of July 15, 2024.",2315182.0,8/5/2024
8,9,McKesson,MCK,Health Care,Wholesalers: Health Care,yes,no,no,no,0,...,62320.0,Brian S. Tyler,U.S.,Irving,Texas,https://www.mckesson.com,Public,"Figures are for fiscal year ended March 31, 20...",75007.0,8/5/2024
9,10,Cencora,COR,Health Care,Wholesalers: Health Care,yes,no,no,yes,1,...,62558.7,Steven H. Collis,U.S.,Conshohocken,Pennsylvania,https://www.cencora.com,Public,"Figures are for fiscal year ended Sept. 30, 20...",43758.0,8/5/2024

In [11]:
df.head(10).isnull()

,Rank,Company,Ticker,Sector,Industry,Profitable,Founder_is_CEO,FemaleCEO,Growth_in_Jobs,Change_in_Rank,...,Assets_M,CEO,Country,HeadquartersCity,HeadquartersState,Website,CompanyType,Footnote,MarketCap_Updated_M,Updated
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,True,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,True,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,True,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,True,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,True,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [12]:
df.head(10).isnull().sum()

Rank                             0
Company                          5
Ticker                           5
Sector                           0
Industry                         0
Profitable                       0
Founder_is_CEO                   0
FemaleCEO                        0
Growth_in_Jobs                   0
Change_in_Rank                   0
Gained_in_Rank                   0
Dropped_in_Rank                  0
Newcomer_to_the_Fortune500       0
Global500                        0
Worlds_Most_Admired_Companies    0
Best_Companies_to_Work_For       0
Number_of_employees              0
MarketCap_March28_M              0
Revenues_M                       0
RevenuePercentChange             0
Profits_M                        0
ProfitsPercentChange             2
Assets_M                         0
CEO                              0
Country                          0
HeadquartersCity                 0
HeadquartersState                0
Website                          0
CompanyType                      0
Footnote                         0
MarketCap_Updated_M              0
Updated                          0
dtype: int64

In [13]:
df.head(10).isnull().sum().sum()

12

In [17]:
df.head(10).notnull().sum().sum()

308

In [19]:
# Series
import numpy as np
sr=pd.Series([1,2,3,np.nan,4,np.NAN])
sr

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    NaN
dtype: float64

In [21]:
sr.isnull()

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [22]:
sr.isnull().sum()

2